const products=[
    {
        id:1,
        img:'/images/projects/garage.png',
        grid:true,
        name:'Car Garage E-commerce',
        p:'A Themeforest cloned project which is an e-commerce shop built using Bootstrap and React that contains filtering by price range, categories, the ability to add and remove items from cart , a single product page ,and pagination without using libraries.',
        bootstrap:true,
        sass:true,
        css:false,
        reduxtoolkit:true,
        react:true,
        fakeData:true,
        api:false,
        link:'https://car-garage-ecommerce.vercel.app/',
        git:'https://github.com/ahmed24666/Car-Garage-Ecommerce',
    },
    {
        id:2,
        img:'/images/projects/ecommerceshop.webp',
        grid:true,
        name:'modern e-commerce',
        p:'A Themeforest cloned project which is an e-commerce shop that contains a trending products slider, dark mode, live search within products, filtering by price range, categories, and owners, all at the same time. It also includes local storage, the ability to add and remove items from cart and favorites, and a single product page.',
        bootstrap:false,
        sass:true,
        css:false,
        react:true,
        fakeData:true,
        api:false,
        link:'https://modern-ecommerce-shop.netlify.app/',
        git:'https://github.com/ahmed24666/Modern-Ecommerce',
    },
    {
        id:3,
        img:'/images/projects/dashboard.png',
        grid:true,
        name:'Multi-themed Dashboard',
        p:'Fully Responsive Multi-themed Dashboard website that contains dark mode, Charts, Tables and local storage. ',
        bootstrap:true,
        sass:true,
        css:false,
        react:true,
        fakeData:true,
        api:false,
        link:'https://aoe-dashboard.vercel.app/',
        git:'https://github.com/ahmed24666/Aoe-Dashboard',
    },
    {
        id:4,
        img:'/images/projects/ship.webp',
        grid:true,
        name:'Yachts e-commerce',
        p:'A Themeforest cloned project which is an Ecommerce shop which contain :  Filtering by price from high to low & vice versa and by categories , Add & remove from cart , Single product page , Modals , Responsive design .',
        bootstrap:false,
        sass:true,
        css:false,
        react:true,
        fakeData:true,
        api:false,
        link:'https://yachts-company-aoe.vercel.app/',
        git:'https://github.com/ahmed24666/Yachts-Company',
    },
    {
        id:5,
        img:'/images/projects/Weather.png',
        grid:true,
        name:'Weather application',
        p:'A Weather application built using two apis, one of them was used to get the cities and their latitude and longitude and the other was used to get the forecast.',
        bootstrap:false,
        sass:true,
        css:false,
        react:true,
        fakeData:false,
        api:true,
        link:'https://weather-app-aoe.vercel.app/',
        git:'https://github.com/ahmed24666/Weather-App',
    },
    {
        id:6,
        img:'/images/projects/burber.webp',
        grid:true,
        name:'barber shop',
        p:'A Themeforest cloned project which is a barber shop website without any libraries for Modals and Carousels , Responsive design , Filtering , and Single team page , Animation On Scroll .',
        bootstrap:false,
        sass:true,
        css:false,
        react:true,
        fakeData:true,
        api:false,
        link:'https://barber-shop-aoe.vercel.app/',
        git:'https://github.com/ahmed24666/Barber-Shop',
    },
    {
        id:7,
        img:'/images/projects/Social.webp',
        grid:true,
        name:'react social media app',
        p:'Login page, Email: any, pass: any, Protected routes, Local storage for Dark mode and Login, Single profile page, Responsive design, Note: you can open the comments.',
        bootstrap:false,
        sass:true,
        css:false,
        react:true,
        fakeData:false,
        api:false,
        link:'https://react-social-media-app-theta.vercel.app/',
        git:'https://github.com/ahmed24666/React-Social-Media-App',
    },
    {
        id:8,
        img:'/images/projects/hotel.webp',
        grid:true,
        name:'modern hotel',
        p:'A Themeforest cloned project which is a Modern Hotel website without any libraries for Carousels, Responsive design, Animation On Scroll.',
        bootstrap:false,
        sass:true,
        css:false,
        react:true,
        fakeData:false,
        api:false,
        link:'https://modern-hotel-aoe.vercel.app/',
        git:'https://github.com/ahmed24666/Modern-Hotel',
    },
    {
        id:9,
        img:'/images/projects/Quiz.webp',
        grid:true,
        name:'quiz app admin panel',
        p:'Email : admin@gmail.com , Pass:0123456789 , A project which was done with a team of backend , android devs and me for the frontend , I was responsible for creating all forms and posting data , I know that posting data and protecting the routes are from backend tasks but I was just tring so there is an error in protecting routes .',
        bootstrap:false,
        sass:true,
        css:false,
        react:true,
        fakeData:false,
        api:true,
        link:'https://quiz-app-admin-panel.vercel.app/',
        git:'https://github.com/ahmed24666/Quiz-App-Admin-Panel',
    },
    {
        id:10,
        img:'/images/projects/restaurant.webp',
        grid:true,
        name:'modern restaurant',
        p:'Restaurant website with Responsive design , Animation On Scroll .',
        bootstrap:false,
        sass:false,
        css:true,
        react:true,
        fakeData:false,
        api:false,
        link:'https://modern-restaurant-aoe.vercel.app/',
        git:'https://github.com/ahmed24666/Modern-Restaurant',
    },
    
]
export default products